### ISSUE TITLE
is is possible to convert HL7 v2 message to json using this lib

### ISSUE THREAD

**Issue by chrisrana** [johnpaulett/python-hl7#23]

**Comment by johnpaulett** [comment]
There is no official HL7v2 JSON schema (that I'm aware of).  The newer [HL7 FHIR](https://www.hl7.org/fhir/json.html) does use JSON for it's document.  python-hl7 right now is just geared towards v2 (which is still widely deployed) and does not implement FHIR as [other libraries](https://github.com/smart-on-fhir) provide that functionality.  

That said, I suspect that since hl7.Message is just a bunch of lists under the hood, it is possible to get something out as JSON:
```python
>>> import hl7
>>> import json
>>> from tests.samples import rep_sample_hl7   # the tests/ directory in this git checkout as an example
>>> message = hl7.parse(rep_sample_hl7)
>>> json.dumps(message)
'[[["MSH"], ["|"], ["^~\\\\&"], ["GHH LAB"], ["ELAB-3"], ["GHH OE"], ["BLDG4"], ["200202150930"], [""], [[["ORU"], ["R01"]]], ["CNTRL-3456"], ["P"], ["2.4"]], [["PID"], ["Field1"], [[["Component1"], ["Component2"]]], [[["Component1"], ["Sub-Component1", "Sub-Component2"], ["Component3"]]], [["Repeat1"], ["Repeat2"]]]]'
```

**Comment by ericpan64** [comment]
Question: would this sort of feature make sense to add in this library? I'm interested in looking into a PR though want to make sure it's consistent with the design goals

E.g. from the list representation above, have an output option that's something like:
```javascript
{
   "MSH-1": "|"
   "MSH-2": "^~\\\\&",
   ...,
   "MSH-9": {
      "MSH-9.1": "ORU",
      "MSH-9.2": "R01"
   },
   ...etc
}
```

**Comment by johnpaulett** [comment]
> Question: would this sort of feature make sense to add in this library?

IMO, probably not since there is no official HL7 v2 JSON representation (that I know of), therefore it would be a custom format specific to python-hl7.  If there is an official v2 JSON format, or if other libraries have such a representation defined (HAPI, NextGen Connect, etc), I'd be more open to consider.

Not to say you can't give it a try or create another library that uses python-hl7 to produce JSON.
