### ISSUE TITLE
Unable to send messages with mllp_send

### ISSUE THREAD

**Issue by ChillarAnand** [johnpaulett/python-hl7#24]
When trying to send messages using `mllp_send` it fails with the following error. I am able to send the same message with other tools like HL7 Inspector. 

```sh
$ mllp_send --file lab.hl7 --port 9662 mirth.avilpage.com
Traceback (most recent call last):
  File "/Users/curatech/.virtualenvs/py37/bin/mllp_send", line 8, in <module>
    sys.exit(mllp_send())
  File "/Users/curatech/.virtualenvs/py37/lib/python3.7/site-packages/hl7/client.py", line 236, in mllp_send
    for message in message_stream:
  File "/Users/curatech/.virtualenvs/py37/lib/python3.7/site-packages/hl7/client.py", line 134, in read_stream
    raise MLLPException('buffer not terminated: %s' % _buffer)
hl7.client.MLLPException: buffer not terminated: b'MSH|^~\\&|GHH LAB|ELAB-3|GHH OE|BLDG4|200202150930||ORU^R01|CNTRL-3456|P|2.4\nPID|||555-44-4444||EVERYWOMAN^EVE^E^^^^L|JONES|196203520|F|||153 FERNWOOD DR.^^STATESVILLE^OH^35292||(206)3345232|(206)752-121||||AC555444444||67-A4335^OH^20030520\nOBR|1|845439^GHH OE|1045813^GHH LAB|1554-5^GLUCOSE|||200202150730||||||||555-55-5555^PRIMARY^PATRICIA P^^^^MD^^LEVEL SEVEN HEALTHCARE, INC.|||||||||F||||||444-44-4444^HIPPOCRATES^HOWARD H^^^^MD\nOBX|1|SN|1554-5^GLUCOSE^POST 12H CFST:MCNC:PT:SER/PLAS:QN||^182|mg/dl|70_105|H|||F'
```

Test message

```
MSH|^~\&|GHH LAB|ELAB-3|GHH OE|BLDG4|200202150930||ORU^R01|CNTRL-3456|P|2.4
PID|||555-44-4444||EVERYWOMAN^EVE^E^^^^L|JONES|196203520|F|||153 FERNWOOD DR.^^STATESVILLE^OH^35292||(206)3345232|(206)752-121||||AC555444444||67-A4335^OH^20030520
OBR|1|845439^GHH OE|1045813^GHH LAB|1554-5^GLUCOSE|||200202150730||||||||555-55-5555^PRIMARY^PATRICIA P^^^^MD^^LEVEL SEVEN HEALTHCARE, INC.|||||||||F||||||444-44-4444^HIPPOCRATES^HOWARD H^^^^MD
OBX|1|SN|1554-5^GLUCOSE^POST 12H CFST:MCNC:PT:SER/PLAS:QN||^182|mg/dl|70_105|H|||F
```

**Comment by johnpaulett** [comment]
lab.hl7 is not actually HL7.  In the last line of the stack trace, you can see how the [segment separators](http://healthstandards.com/blog/2007/09/24/hl7-separator-characters/) are now newlines (`\n`) instead of a carriage returns (`\r`), e.g. between the MSH and PID segments, `P|2.4\nPID`.  This is one of the frustrating things about HL7 -- while it looks like a text-based message and we commonly want to use text editors, it really is a binary message that uses specific ASCII characters to indicate end of segment and end of message that will get corrupted by a text editor.

The good news is that mllp_send has the [--loose flag](http://healthstandards.com/blog/2007/09/24/hl7-separator-characters/) to treat this file that "looks like HL7" as HL7.

```
mllp_send --loose --file lab.hl7 --port 9662 mirth.avilpage.com
```

One note about --loose, it will assume the file only contains a single HL7 message.  The non-loose mode can use the HL7 file separator character (`\x1c`), to split multiple messages in the same file.

**Comment by ChillarAnand** [comment]
Thanks for the detailed information. @johnpaulett 

Should this option be added to the documentation?

**Comment by johnpaulett** [comment]
Sure. 

Sorry, my second link was incorrectly pasted, https://python-hl7.readthedocs.io/en/latest/mllp_send.html#input-format -- so there is some documentation, but happy to consider additional clarity.

**Comment by ChillarAnand** [comment]
That should be fine. I was looking at https://python-hl7.readthedocs.io/en/latest/index.html#mllp-network-client-mllp-send and missed this page. 

Thank you for maintaining python-hl7 package and for the prompt response.
